global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']
  - job_name: 'nextjs'
    metrics_path: '/api/metrics'
    static_configs:
      - targets: ['your-domain.com']

rule_files:
  - 'prometheus.rules.yml'
